apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      initContainers:
      - name: busybox-container
        image: busybox
        volumeMounts:
        - name: myvol
          mountPath: /data
        command: ["/bin/sh"]
        args: ["-c","echo '<h1>Hello from initContainer</h1>' > /data/index.html"]

      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html
      
      volumes:
      - name: myvol
        emptyDir: {}
