apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
spec:
  selector:
    matchLabels:
      app: nginx-stateful
  serviceName: nginx-stateful-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-stateful
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-stateful-vol
          mountPath: /usr/share/nginx/html
  
  volumeClaimTemplates:
  - metadata:
      name: nginx-stateful-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 500Mi